# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_de', models.CharField(max_length=200, verbose_name='Title (de)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title (en)')),
            ],
            options={
                'verbose_name': 'Entry Category',
                'verbose_name_plural': 'Entry Categories',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='ideas', to='test_app.Category', verbose_name='Categories'),
        ),
    ]
