# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_de', models.CharField(max_length=200, verbose_name='Title (de)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title (en)')),
                ('description_de', models.TextField(blank=True, verbose_name='Description (de)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (en)')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
